# Generated by Django 4.0.2 on 2022-03-04 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_user'),
        ('account', '0002_alter_account_token'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactNumberOnBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reacts', models.PositiveBigIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='ReactBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, null=True)),
                ('dislike', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
        ),
    ]
