# Generated by Django 4.0.2 on 2022-03-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_reactnumberonblog_reactblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactnumberonblog',
            old_name='number_of_reacts',
            new_name='number_of_dislikes',
        ),
        migrations.AddField(
            model_name='reactnumberonblog',
            name='number_of_likes',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
