# Generated by Django 4.0.2 on 2022-03-01 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('token', models.CharField(max_length=30, null=True, unique=True)),
                ('password', models.CharField(max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
