# Generated by Django 4.0.2 on 2022-03-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
