# Generated by Django 4.0.2 on 2022-03-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, default='default/no-image.jpg', null=True, upload_to='blog/images'),
        ),
    ]
